import type { Invoice } from "@/types/types";

const invoices: Invoice[] = [
  {
    id: 1,
    invoiceNumber: "INV-001",
    date: "2022-01-01",
    client: "John Doe",
    amount: 100,
    status: "draft",
    description: "Graphic Design",
  },
  {
    id: 2,
    invoiceNumber: "INV-002",
    date: "2022-02-01",
    client: "Jane Doe",
    amount: 200,
    status: "pending",
    description: "Web Development",
  },
  {
    id: 3,
    invoiceNumber: "INV-003",
    date: "2022-03-01",
    client: "Bob Smith",
    amount: 300,
    status: "paid",
    description: "Software Development",
  },
  {
    id: 4,
    invoiceNumber: "INV-004",
    date: "2022-04-01",
    client: "Alice Johnson",
    amount: 400,
    status: "draft",
    description: "Web Development",
  },
  {
    id: 5,
    invoiceNumber: "INV-005",
    date: "2022-05-01",
    client: "Charlie Brown",
    amount: 500,
    status: "pending",
    description: "Graphic Design",
  },
  {
    id: 6,
    invoiceNumber: "INV-006",
    date: "2022-06-01",
    client: "Eve Green",
    amount: 600,
    status: "paid",
    description: "Software Development",
  },
  {
    id: 7,
    invoiceNumber: "INV-007",
    date: "2022-07-01",
    client: "Frank White",
    amount: 700,
    status: "draft",
    description: "UI/UX Design",
  },
  {
    id: 8,
    invoiceNumber: "INV-008",
    date: "2022-08-01",
    client: "Grace Blue",
    amount: 800,
    status: "pending",
    description: "Mobile Development",
  },
  {
    id: 9,
    invoiceNumber: "INV-009",
    date: "2022-09-01",
    client: "Harry Red",
    amount: 900,
    status: "paid",
    description: "Backend Development",
  },
  {
    id: 10,
    invoiceNumber: "INV-010",
    date: "2022-10-01",
    client: "Ivy Yellow",
    amount: 1000,
    status: "draft",
    description: "Logo Design",
  },
  {
    id: 11,
    invoiceNumber: "INV-011",
    date: "2022-11-01",
    client: "Jack Green",
    amount: 1100,
    status: "pending",
    description: "Frontend Development",
  },
  {
    id: 12,
    invoiceNumber: "INV-012",
    date: "2022-12-01",
    client: "Kate Blue",
    amount: 1200,
    status: "paid",
    description: "Data Analysis",
  },
];
export { invoices };
